export const LOGGED_IN_USER = "LOGGED_IN_USER";

export const FETCH_DOCTOR_APPOINTMENT_LIST = "FETCH_DOCTOR_APPOINTMENT_LIST";
export const FETCH_DOCTOR_APPOINTMENT_LIST_SUCCESS = "FETCH_DOCTOR_APPOINTMENT_LIST_SUCCESS";
export const FETCH_DOCTOR_APPOINTMENT_LIST_ERROR = "FETCH_DOCTOR_APPOINTMENT_LIST_ERROR";

export const FETCH_PATIENTS_APPOINTMENT_LIST = "FETCH_PATIENTS_APPOINTMENT_LIST";
export const FETCH_PATIENTS_APPOINTMENT_LIST_SUCCESS = "FETCH_PATIENTS_APPOINTMENT_LIST_SUCCESS";
export const FETCH_PATIENTS_APPOINTMENT_LIST_ERROR = "FETCH_PATIENTS_APPOINTMENT_LIST_ERROR";

export const SET_LOADER = "SET_LOADER";
